name: housing-stat
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.11
  - ipykernel
  - pandas
prefix: C:\Users\alion\anaconda3\envs\housing-stat
